services:
  controller:
    image: notebookum-controller:v1.0.0
    restart: unless-stopped
    networks:
      notebookum-network:
        aliases:
          - api.universidad.localhost
    environment:
      PORT: "5000" 
      EXTRACTOR_URL: "https://extractor.universidad.localhost"
      AI_URL: "https://ai.universidad.localhost"
      PERSISTENCE_URL: "https://persistence.universidad.localhost"
      USER_SERVICE_URL: "https://users.universidad.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller.rule=Host(`api.universidad.localhost`) && PathPrefix(`/api/v1/`)"
      - "traefik.http.routers.controller.entryPoints=https"
      - "traefik.http.routers.controller.tls=true"
      - "traefik.http.services.controller.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.bulkhead-controller.inflightreq.amount=50"
      - "traefik.http.routers.controller.middlewares=bulkhead-controller"

networks:
  notebookum-network:
    external: true
