rules:
  - route_pattern: "POST /api/v1/users"
    destination: "service-user"
    enabled: true
  - route_pattern: "GET /api/v1/users/:id"
    destination: "service-user"
    enabled: true
  - route_pattern: "POST /api/v1/documento/upload"
    destination: "service-extractor"
    enabled: true
  - route_pattern: "GET /api/v1/summaries/document/:id"
    destination: "service-persistence"
    enabled: true
